CREATE TABLE [tmp].[20210514_cew_data] (
  [ID] [nvarchar](500) NULL,
  [SupPartyName] [nvarchar](500) NULL,
  [SupPartyRegName] [nvarchar](500) NULL,
  [NombreTienda] [nvarchar](500) NULL,
  [CodigoMall] [nvarchar](500) NULL,
  [CodigoTienda] [nvarchar](500) NULL,
  [RucEmisor] [nvarchar](500) NULL,
  [IdentificadorTerminal] [nvarchar](1) NULL,
  [NumeroTerminal] [nvarchar](500) NULL,
  [Serie] [nvarchar](500) NULL,
  [TipoTransaccion] [nvarchar](500) NULL,
  [NumeroTransaccion] [nvarchar](500) NULL,
  [Fecha] [nvarchar](500) NULL,
  [Hora] [nvarchar](500) NULL,
  [Cajero] [nvarchar](500) NULL,
  [Vendedor] [nvarchar](500) NULL,
  [DNI] [nvarchar](500) NULL,
  [RUC] [nvarchar](500) NULL,
  [CusPartyRegName] [nvarchar](500) NULL,
  [Direccion] [nvarchar](2000) NULL,
  [Moneda] [nvarchar](500) NULL,
  [MedioPago] [nvarchar](1) NULL,
  [TotalValorVentaBruta] [nvarchar](20) NULL,
  [CargosDescuentosGlobal] [nvarchar](500) NULL,
  [MontoTotalIgv] [nvarchar](20) NULL,
  [TotalValorVentaNeta] [nvarchar](20) NULL,
  [Orden] [nvarchar](500) NULL,
  [CantidadUnidadesItem] [nvarchar](20) NULL,
  [CodigoProducto] [nvarchar](500) NULL,
  [DescripcionProducto] [nvarchar](500) NULL,
  [PrecioVentaUnitarioItem] [nvarchar](20) NULL,
  [CargoDescuentoItem] [nvarchar](20) NULL,
  [PrecioTotalItem] [nvarchar](20) NULL
)
ON [PRIMARY]
GO